CREATE USER AD_ACADEMIA IDENTIFIED BY AD_ ACADEMIA;
GRANT DBA TO AD_ ACADEMIA;
CREATE TABLE ALUMNOS(
 cCodAlu VARCHAR2(6) CONSTRAINT PK_ALUMNOS PRIMARY KEY,
 cNomAlu VARCHAR2(100) NOT NULL
);
CREATE TABLE CURSOS(
 cCodCurso VARCHAR2(6) CONSTRAINT PK_CURSOS PRIMARY KEY,
 cNomCurso VARCHAR2(100) NOT NULL,
 nNumExa NUMBER(3) DEFAULT 1 NOT NULL
);
CREATE TABLE MATRICULAS(
 cCodAlu VARCHAR2(6) NOT NULL,
 cCodCurso VARCHAR2(6) NOT NULL,
 nNotaMedia NUMBER(3) DEFAULT 0 NOT NULL,
 CONSTRAINT PK_MATRICULAS PRIMARY KEY (cCodAlu,cCodCurso)
);
ALTER TABLE MATRICULAS
ADD CONSTRAINT FK_MATRICULAS_ALUMNO FOREIGN KEY (cCodAlu)
REFERENCES ALUMNOS(cCodAlu);
ALTER TABLE MATRICULAS
ADD CONSTRAINT FK_MATRICULAS_CURSOS FOREIGN KEY (cCodCurso)
REFERENCES CURSOS(cCodCurso);
CREATE TABLE EXAMENES(
 cCodAlu VARCHAR2(6) NOT NULL,
 cCodCurso VARCHAR2(6) NOT NULL,
 nNumExam NUMBER(3) DEFAULT 1 NOT NULL,
 dFecExam DATE,
 nNotaExam NUMBER(6,2) DEFAULT 0 NOT NULL,
 CONSTRAINT PK_EXAMENES PRIMARY KEY (cCodAlu,cCodCurso,nNumExam)
);
ALTER TABLE EXAMENES
ADD CONSTRAINT FK_EXAMENES_MATR FOREIGN KEY (cCodAlu,cCodCurso)
REFERENCES MATRICULAS(cCodAlu,cCodCurso);
INSERT INTO ALUMNOS VALUES ('001','Antonio');
INSERT INTO ALUMNOS VALUES ('002','Maria');
INSERT INTO CURSOS VALUES ('I001','Ingles Basico',5);
INSERT INTO CURSOS VALUES ('I002','Ingles Intermedio',8);
INSERT INTO CURSOS VALUES ('I003','Ingles Avanzado',10);
INSERT INTO CURSOS VALUES ('F001','Frances Basico',3);
INSERT INTO CURSOS VALUES ('C002','Chino Intermedio',9);
COMMIT;
CREATE OR REPLACE PROCEDURE SP_ALTAMATRICULA (XCCODALU VARCHAR2, XCCODCURSO VARCHAR2, XERROR OUT
varchar2)
IS
 xNR NUMBER;
BEGIN
 xError := '';
 INSERT INTO MATRICULAS VALUES (xcCodAlu, xcCodCurso,0);
 SELECT nNumExa INTO xNR FROM CURSOS WHERE cCodCurso = xcCodCurso;
 FOR i IN 1..xNR LOOP
 INSERT INTO EXAMENES (cCodAlu,cCodCurso,nNumExam) VALUES (xcCodAlu, xcCodCurso,i);
 END LOOP;
-- xError := xNR;
EXCEPTION
 WHEN OTHERS THEN XERROR := SQLERRM;
END;
select * FROM MATRICULAS;
SELECT * FROM USER_CONSTRAINTS;
SET SERVEROUTPUT ON;
DECLARE
error number;
BEGIN
  sp_AltaMatricula('003','F001',error);
END;