--CREATE USER AD_HIBERNATE1 IDENTIFIED BY AD_HIBERNATE1;
--GRANT DBA TO AD_HIBERNATE1;

CREATE TABLE CLIENTE(
  CODIGO VARCHAR2(10),
  NOMBRE VARCHAR2(20),
  TELEFONO NUMBER(90)
);

CREATE TABLE UBICACION(
  CODIGO_CLIENTE VARCHAR2(10),
  CIUDAD VARCHAR2(20),
  CALLE VARCHAR2(30)
);

CREATE TABLE COMPRAS(
  CODIGO_CLIENTE VARCHAR2(20),
  CODIGO_PRODUCTO VARCHAR2(20),
  PRECIO NUMBER(3,2),
  NUMPRODUCTOS NUMBER(3)
);

ALTER TABLE