  --CREATE USER AD_TEMA02 IDENTIFIED BY AD_TEMA02;
--GRANT DBA TO AD_TEMA02;
--Desde el usuario/esquema AD_TEMA02
CREATE TABLE ALUMNOS(
 cCodAlu VARCHAR2(6) CONSTRAINT PK_ALUMNOS PRIMARY KEY,
 cNomAlu VARCHAR2(100) NOT NULL
);
CREATE TABLE CURSOS(
 cCodCurso VARCHAR2(6) CONSTRAINT PK_CURSOS PRIMARY KEY,
 cNomCurso VARCHAR2(100) NOT NULL,
 nNumExa NUMBER(3) DEFAULT 1 NOT NULL 
);
CREATE TABLE MATRICULAS(
 cCodAlu VARCHAR2(6) NOT NULL,
 cCodCurso VARCHAR2(6) NOT NULL,
 nNotaMedia NUMBER(3) DEFAULT 0 NOT NULL,
 CONSTRAINT PK_MATRICULAS PRIMARY KEY (cCodAlu,cCodCurso)
);
ALTER TABLE MATRICULAS ADD CONSTRAINT FK_MATRICULAS_ALUMNO FOREIGN KEY (cCodAlu)
REFERENCES ALUMNOS(cCodAlu);
ALTER TABLE MATRICULAS ADD CONSTRAINT FK_MATRICULAS_CURSOS FOREIGN KEY (cCodCurso)
REFERENCES CURSOS(cCodCurso);
CREATE TABLE EXAMENES(
 cCodAlu VARCHAR2(6) NOT NULL,
 cCodCurso VARCHAR2(6) NOT NULL,
 NNUMEXAM NUMBER(3) DEFAULT 1 NOT NULL,
 dFecExam varchar2(10),
 nNotaExam NUMBER(6,2) DEFAULT 0 NOT NULL,
 CONSTRAINT PK_EXAMENES PRIMARY KEY (cCodAlu,cCodCurso,nNumExam)
);
DELETE FROM MATRICULAS;
drop table examenes;
ALTER TABLE EXAMENES ADD CONSTRAINT FK_EXAMENES_MATR FOREIGN KEY (cCodAlu,cCodCurso)
REFERENCES MATRICULAS(cCodAlu,cCodCurso);
INSERT INTO ALUMNOS VALUES ('001','Antonio');
INSERT INTO ALUMNOS VALUES ('002','Maria');
INSERT INTO CURSOS VALUES ('I001','Ingles Basico',5);
INSERT INTO CURSOS VALUES ('I002','Ingles Intermedio',8);
INSERT INTO CURSOS VALUES ('I003','Ingles Avanzado',10);
INSERT INTO CURSOS VALUES ('F001','Frances Basico',3);
INSERT INTO CURSOS VALUES ('C002','Chino Intermedio',9);
COMMIT;
CREATE OR REPLACE PROCEDURE sp_AltaMatricula (xcCodAlu VARCHAR2, xcCodCurso VARCHAR2, xError OUT 
NUMBER)
IS XNR NUMBER;
  NUMEXAMENES NUMBER := 0;
  INDX NUMBER := 1;
BEGIN
  SELECT NNUMEXA INTO NUMEXAMENES FROM CURSOS WHERE cCodCurso = xcCodCurso;
  INSERT INTO MATRICULAS VALUES (XCCODALU,XCCODCURSO,0);
  FOR INDX IN 1..NUMEXAMENES LOOP
    INSERT INTO EXAMENES VALUES (XCCODALU,XCCODCURSO,INDX,NULL,0);
  END LOOP; 
EXCEPTION
 WHEN OTHERS THEN xError := -1;
END;
CREATE OR REPLACE PROCEDURE SP_EXAMEN(XCCODALU VARCHAR2, XCCODCURSO VARCHAR2,XERROR OUT NUMBER)
IS XNR NUMBER;
  LINEAS NUMBER := 0;
  SUMA NUMBER := 0;
BEGIN
  SELECT COUNT(*),SUM(NNOTAEXAM) INTO LINEAS,SUMA FROM EXAMENES WHERE NNOTAEXAM > 0;
  UPDATE MATRICULAS SET nNotaMedia = (SUMA/LINEAS) where cCodAlu = xcCodCurso and cCodCurso = xcCodCurso;
EXCEPTION
  WHEN OTHERS THEN XERROR:= -1;
END;
COMMIT;
SELECT * FROM ALUMNOS;
SELECT * FROM CURSOS;

SELECT * FROM MJ;
SELECT * FROM EXAMENES;

CREATE OR REPLACE VIEW MJ AS
(SELECT MAT.CCODALU,ALU.CNOMALU,MAT.CCODCURSO,CUR.CNOMCURSO,MAT.NNOTAMEDIA
FROM CURSOS CUR, MATRICULAS MAT, ALUMNOS ALU
WHERE CUR.CCODCURSO = MAT.CCODCURSO AND MAT.CCODALU = ALU.CCODALU
GROUP BY MAT.CCODALU,ALU.CNOMALU,MAT.CCODCURSO,CUR.CNOMCURSO,MAT.NNOTAMEDIA);
SELECT * FROM MJ;
SELECT * FROM MATRICULAS;