/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication7;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author usuario
 */
public class JFrame extends javax.swing.JFrame {
    private final FileNameExtensionFilter filtrotxt;
    /**
     * Creates new form JFrame
     */
    public JFrame() {
        this.filtrotxt = new FileNameExtensionFilter("TEXT FILES", "txt", "text");
        initComponents();
        this.jb_Fichero2.setEnabled(false);
        this.jtf_Fichero2.setEditable(false);
        this.jb_comprobar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtf_Fichero1 = new javax.swing.JTextField();
        jtf_Fichero2 = new javax.swing.JTextField();
        jb_Fichero1 = new javax.swing.JButton();
        jb_Fichero2 = new javax.swing.JButton();
        jb_comprobar = new javax.swing.JButton();
        jl_fin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(520, 300));
        setResizable(false);

        jLabel1.setText("Fichero 1:");

        jLabel2.setText("Fichero 2:");

        jb_Fichero1.setText("Seleccion del Fichero 1");
        jb_Fichero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_Fichero1ActionPerformed(evt);
            }
        });

        jb_Fichero2.setText("Seleccion del Fichero 2");
        jb_Fichero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_Fichero2ActionPerformed(evt);
            }
        });

        jb_comprobar.setText("Comprobar Ficheros");
        jb_comprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_comprobarActionPerformed(evt);
            }
        });

        jl_fin.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 149, Short.MAX_VALUE)
                        .addComponent(jb_comprobar, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_Fichero2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtf_Fichero1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                            .addComponent(jtf_Fichero2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jb_Fichero1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(jl_fin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtf_Fichero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_Fichero1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtf_Fichero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_Fichero2))
                .addGap(18, 18, 18)
                .addComponent(jb_comprobar)
                .addGap(18, 18, 18)
                .addComponent(jl_fin)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jb_Fichero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_Fichero1ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setFileFilter(this.filtrotxt);
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            this.jl_fin.setText(" ");
            this.jtf_Fichero1.setText(fileChooser.getSelectedFile().getAbsolutePath());
            this.jtf_Fichero2.setEditable(true);
            this.jb_Fichero2.setEnabled(true);
        }else{
            JOptionPane.showMessageDialog(this,"No ha encontrado el fichero");
        }
    }//GEN-LAST:event_jb_Fichero1ActionPerformed

    private void jb_Fichero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_Fichero2ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setFileFilter(this.filtrotxt);
        this.jl_fin.setText(" ");
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            this.jtf_Fichero2.setText(fileChooser.getSelectedFile().getAbsolutePath());
            this.jb_comprobar.setEnabled(true);
        }else{
            JOptionPane.showMessageDialog(this,"No ha encontrado el fichero");
        }
    }//GEN-LAST:event_jb_Fichero2ActionPerformed

    private void jb_comprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_comprobarActionPerformed
        this.jl_fin.setText(" ");
        File f1 = new File(this.jtf_Fichero1.getText());
        File f2 = new File(this.jtf_Fichero2.getText());
        FileReader fr1;
        FileReader fr2;
        String fr1String;
        String fr2String;
        
        if (f1.exists() && f2.exists()) {
            try {
                fr1 = new FileReader(f1);
                fr2 = new FileReader(f2);
                fr1String= this.toS(fr1);
                fr2String= this.toS(fr2);
                if (fr1String.equals(fr2String)) {
                    this.jl_fin.setText("Son iguales");
                }else{
                    this.jl_fin.setText("Son diferentes");
                }
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "No se ha encontrado el fichero");
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Error a la hora de leer el fichero");
            }
            
        }else{
            if (f1.exists()) {
                JOptionPane.showMessageDialog(this,"No ha encontrado el fichero 1");
            }else{
                JOptionPane.showMessageDialog(this,"No ha encontrado el fichero 2");
            }
        }
    }//GEN-LAST:event_jb_comprobarActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jb_Fichero1;
    private javax.swing.JButton jb_Fichero2;
    private javax.swing.JButton jb_comprobar;
    private javax.swing.JLabel jl_fin;
    private javax.swing.JTextField jtf_Fichero1;
    private javax.swing.JTextField jtf_Fichero2;
    // End of variables declaration//GEN-END:variables
    public String toS(FileReader file) throws IOException{
        int aux1 = 1;
        String aux2 = "";
        while(aux1 >= 0){
            aux1 = file.read();
            aux2 += (char)aux1;
            System.out.println(aux2);
        }
        file.close();
        return aux2;
    }
}
